name: mjpc_lowdim
obs_dim: 14 # spline(11) + pos(2) + vel(2)
action_dim: 11 # u(1) + spline(11)

dataset:
  _target_: diffusion_policy.dataset.mjpc_lowdim_dataset.MJPCLowdimDataset
  zarr_path: /home/ali/super_isolated/mujoco_mpc/python/mujoco_mpc/demos/agent/trajectories/pkls/_replay_buffer.zarr
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1+${n_latency_steps}'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.02
  max_train_episodes: 90
